version = "0.1dev"
author = "Nathan Vack"
author_email = "njvack@wisc.edu"
license = "MIT"
copyright = "Copyright 2014 Boards of Regent of the University of Wisconsin System"
url = "https://github.com/njvack/scorify"